name: web_toast
description: A small framework-agnostic library for displaying popup info
  messages ("toasts") in web apps
version: 1.0.0-nullsafety
homepage: https://www.github.com/afpatmin/toast
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4  
  sass_builder: ^2.1.3
